on: push

jobs:
  automation_controller_job:
    runs-on: ubuntu-latest
    name: Kick off Automation controller job
    steps:
      - name: Load the ansible-cloud action
        id: controller_job
        uses: mhyclak-silex/aap_controller_action@main
        with:
          controller_host: https://student1.rh6b97.example.opentlc.com/
          controller_username: ${{ secrets.CONTROLLER_USERNAME }}
          controller_password: ${{ secrets.CONTROLLER_PASSWORD }}
          controller_project: "Silex Ansible Workshop Project"
          job_template: "Deploy Webapp"
          extra_vars: "aw_app_branch=main"
          validate_certs: false
